### ISSUE TITLE
[eslint] i can't found fix "import/no-extraneous-dependencies"

### ISSUE THREAD

**Issue by nililia** [novemberborn/babel-plugin-import-glob#36]
#35 
i can't found fix "import/no-extraneous-dependencies"
I need your help

but can fix "no-unresolved"
```javascript
// file: '.eslintrc'
// fix: no-unresolved
{
    "extends": "airbnb",
    "rules": {
        "import/no-unresolved": [
            "error",
            {
                "ignore": [
                    "^glob:"
                ]
            }
        ]
    }
}
```

**Comment by novemberborn** [comment]
Yea, it might be that `eslint-plugin-import` doesn't support this. See https://github.com/benmosher/eslint-plugin-import/issues/340#issuecomment-256676710.

[Add a comment to disable the rule](http://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) instead:

```js
import * from 'glob:routes/*.js' // eslint-disable-line import/no-extraneous-dependencies
```

---

P.S. there's no need to open an new issue, you can add comments to closed issues. I'm closing these aggressively since this is not a repository I look at often, and it's not an issue with the module itself.
