### ISSUE TITLE
import named exports from pattern matches

### ISSUE THREAD

**Issue by dominikstoetter** [novemberborn/babel-plugin-import-glob#53]
Hi, thanks for the really helpful plugin.

i cannot however import named exports from a module file. The plugin only imports the default export. 

example:

```
//cool.module.js
export const awesome = 'yay'
export default 'not so yay'
```

```
//index.js
import { awesome } from './**/*.module.js'
//Syntax error: Could not match import 'watchers' to a module. Available members are 'cool'
```

this would import the default import: 
```
//index.js
import * as default from './**/*.module.js'
//default === 'not so yay'
```

**Comment by novemberborn** [comment]
Glad you like it @dominikstoetter!

> The plugin only imports the default export.

Yes, this is by design. The glob patterns are expected to match multiple files. Identifiers are generated based on each filename. It's those generated identifiers that you can import.

There is no way syntactically to express "import {awesome} from the matched file named 'cool'". Just like there's no way to express "import all {awesome} exports from all matched files". Your best bet is to export a default object with multiple properties and then write some code that can extract the expected value.
