### ISSUE TITLE
globstar not finding first level files

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [novemberborn/babel-plugin-import-glob#55]
Hi

My file structure is as following: 
```
src
 |- root.js
 |- components
   |- foo.js 
   |- bar.js
   |- baz
    |- baz.js
    |- baz.css
```

In `root.js` I use the following import:

```js
import * as Components from "./components/**/*.js";
```

which partially works, as `Components` only contains `baz.js`.

I would expect `foo.js` and `bar.js` to also be imported.

**Comment by novemberborn** [comment]
I imagine that's because of the underlying globbing module. Try `./components/{*.js,**/*.js}`. You should then see `foo`, `bar` and `baz`. Though you may get collisions since brace expansions are not considered to be a dynamic portion of the pattern.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)
